Traceback (most recent call last):
  File "/opt/anaconda3/envs/jupyter_book_ml/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/envs/jupyter_book_ml/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/envs/jupyter_book_ml/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/anaconda3/envs/jupyter_book_ml/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/anaconda3/envs/jupyter_book_ml/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/envs/jupyter_book_ml/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/envs/jupyter_book_ml/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Time Series Decomposition
from statsmodels.tsa.seasonal import seasonal_decompose

result_mul = seasonal_decompose(
    df["Average"], model="add", extrapolate_trend="freq", 
)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[14], line 4[0m
[1;32m      1[0m [38;5;66;03m# Time Series Decomposition[39;00m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mstatsmodels[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtsa[39;00m[38;5;21;01m.[39;00m[38;5;21;01mseasonal[39;00m [38;5;28;01mimport[39;00m seasonal_decompose
[0;32m----> 4[0m result_mul [38;5;241m=[39m [43mseasonal_decompose[49m[43m([49m
[1;32m      5[0m [43m    [49m[43mdf[49m[43m[[49m[38;5;124;43m"[39;49m[38;5;124;43mAverage[39;49m[38;5;124;43m"[39;49m[43m][49m[43m,[49m[43m [49m[43mmodel[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43madd[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mextrapolate_trend[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mfreq[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m
[1;32m      6[0m [43m)[49m

File [0;32m/opt/anaconda3/envs/jupyter_book_ml/lib/python3.9/site-packages/statsmodels/tsa/seasonal.py:167[0m, in [0;36mseasonal_decompose[0;34m(x, model, filt, period, two_sided, extrapolate_trend)[0m
[1;32m    165[0m         period [38;5;241m=[39m pfreq
[1;32m    166[0m     [38;5;28;01melse[39;00m:
[0;32m--> 167[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    168[0m             [38;5;124m"[39m[38;5;124mYou must specify a period or x must be a pandas object with [39m[38;5;124m"[39m
[1;32m    169[0m             [38;5;124m"[39m[38;5;124ma PeriodIndex or a DatetimeIndex with a freq not set to None[39m[38;5;124m"[39m
[1;32m    170[0m         )
[1;32m    171[0m [38;5;28;01mif[39;00m x[38;5;241m.[39mshape[[38;5;241m0[39m] [38;5;241m<[39m [38;5;241m2[39m [38;5;241m*[39m pfreq:
[1;32m    172[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    173[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mx must have 2 complete cycles requires [39m[38;5;132;01m{[39;00m[38;5;241m2[39m[38;5;250m [39m[38;5;241m*[39m[38;5;250m [39mpfreq[38;5;132;01m}[39;00m[38;5;124m [39m[38;5;124m"[39m
[1;32m    174[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mobservations. x only has [39m[38;5;132;01m{[39;00mx[38;5;241m.[39mshape[[38;5;241m0[39m][38;5;132;01m}[39;00m[38;5;124m observation(s)[39m[38;5;124m"[39m
[1;32m    175[0m     )

[0;31mValueError[0m: You must specify a period or x must be a pandas object with a PeriodIndex or a DatetimeIndex with a freq not set to None

